### ISSUE TITLE
Snowplow reference older Newtonsoft dll version than unity 2021.3.8f1

### ISSUE THREAD

**Issue by dkjepben** [snowplow/snowplow-unity-tracker#53]
**Describe the bug**
We are upgrading our Unity Project to 2021.3.8f1, however, we get the following error from snowplow dll:

`Assembly 'Assets/Plugins/SnowplowTracker/SnowplowTracker.dll' will not be loaded due to errors:
SnowplowTracker references strong named Newtonsoft.Json Assembly references: 12.0.0.0 Found in project: 13.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"`

And disabling the version validation just hides the error message, but when we run the project we get reflection errors.

This can be reproduced in a new clean Unity project.

The dependency which is causing this error is in service.core, this package is included by standard in Unity and cannot be removed.

`"com.unity.services.core": {
      "version": "1.4.2",
      "depth": 1,
      "source": "registry",
      "dependencies": {
        "com.unity.modules.unitywebrequest": "1.0.0",
        "com.unity.nuget.newtonsoft-json": "3.0.2",
        "com.unity.modules.androidjni": "1.0.0"
      },
      "url": "https://packages.unity.com"
    },`

**To Reproduce**

* Create a Unity project in 2021.3.8f1.
* Include snowplow package 0.5.1.
* See assembly error.

**Expected behavior**

No compiler errors.

**Device and Build Information (please complete the following information):**
 - Device: Editor
 - OS: Mac, Windows
 - Unity Version 2021.3.8f1

**Comment by ameltom** [comment]
Same issue. Please help

**Comment by matus-tomlein** [comment]
Thank you for reporting this issue @dkjepben and @ameltom! We will look into it shortly.
